### ISSUE TITLE
Update INSTALLED_APPS

### ISSUE THREAD

**Issue by ifalko** [adilkhash/django_channels_demo#1]
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'chat',#you must add this line!!!
    'channels',
]
Also after this is:
python manage.py migrate

**Comment by adilkhash** [comment]
Thanks for mentioning. Could you send a Pull Request?

**Comment by adilkhash** [comment]
Actually in order for application to work it is unnecessary to include 'chat' to INSTALLED_APPS because this app does not contain models at all. But It would be great if you send a PR for consistency. Thanks.

**Comment by ifalko** [comment]
Demo does not work correctly and cause difficulty understanding for beginners. I caused, and I spent a little time to fix this. Thx!)

**Comment by adilkhash** [comment]
#2
